### ISSUE TITLE
视频下载问题

### ISSUE THREAD

**Issue by SYL-322** [xyiyy/GIF-Thumbnails#2]
谢谢你的工作！

我发现在根据提供的url下载视频时，有些视频会报错
`you-get: [Error] Invalid video format.`

把you-get命令中指定的 `--format=flv720` 去掉可以下载，我不知道这样去掉会不会影响标注的准确性。

另外还有一些视频的链接已失效，无法下载，请问能否将视频数据集公开？

**Comment by xyiyy** [comment]
感谢你对我们工作的关注！

去掉`--format` 对于标注的影响并不是特别大，因为实际操作时还会被进一步resize，不过可能会在特征上造成一些差异。

对于部分视频链接失效的问题，一到两周内，我们会公开被resize后的视频以及相应的特征。

**Comment by SYL-322** [comment]
> 感谢你对我们工作的关注！
> 
> 去掉`--format` 对于标注的影响并不是特别大，因为实际操作时还会被进一步resize，不过可能会在特征上造成一些差异。
> 
> 对于部分视频链接失效的问题，一到两周内，我们会公开被resize后的视频以及相应的特征。

感谢回答！另外想问一下给几个视频及其对应的gif封面（比如teaser中的狗狗视频），我想确认一下自己的封面提取方式是否有错误。

**Comment by xyiyy** [comment]
Sorry for delaying. We have released the extracted features on the [BaiduDisk](https://pan.baidu.com/s/1o4WjdHLXFb9orle4l3UwMw ) with code `r9p1`. Due to the ethical facts and ownership of videos, we are still applying for the publication of the raw videos.

**Comment by yeliudev** [comment]
> Sorry for delaying. We have released the extracted features on the [BaiduDisk](https://pan.baidu.com/s/1BOeRQDM2It_IG69lQqaidg) with code `g9pa`. Due to the ethical facts and ownership of videos, we are still applying for the publication of the raw videos.

Thanks for releasing the features! It seems that the BaiduDisk link is broken, could you please take a look at it?

**Comment by xyiyy** [comment]
> > Sorry for delaying. We have released the extracted features on the [BaiduDisk](https://pan.baidu.com/s/1BOeRQDM2It_IG69lQqaidg) with code `g9pa`. Due to the ethical facts and ownership of videos, we are still applying for the publication of the raw videos.
> 
> Thanks for releasing the features! It seems that the BaiduDisk link is broken, could you please take a look at it?

Thanks for the comment. I have updated the link above. QAQ. It is broken due to the default maximum visits in settings.

**Comment by yeliudev** [comment]
The link is fine now. Thanks!
